/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CircleImage: typeof import('./src/components/CircleImage.vue')['default']
    LottiPlayer: typeof import('./src/components/lottiPlayer.vue')['default']
    WelcomeText: typeof import('./src/components/welcomeText.vue')['default']
  }
}
